### PR TITLE
Fixed Crimson Roman 'a' kerning

### LINKED ISSUE #66: Crimson Roman 'a' kerning broken
Commit 553aa7b caused a problem with kerning after the letter `a`.

Before that commit, at 5b3f19c, kerning was great:

crimson-roman-at-5b3f19c

But at 553aa7b, this happened:

crimson-roman-at-553aa7b

I don't know enough about the source files to find the exact change that caused the problem.

### PR DESCRIPTION
**Pull request by ghost**
Should definitely fix #66.

### CODE REVIEW

**Comment by jco2** [comment]
I wonder why the last commit made a lot of change... I just adjusted the kerning of the 'a'.

**Comment by skosch** [comment]
@jco2 Thanks for your PR! I'm sorry I'm on the road right now and won't be able to look at this too soon. There's also an entirely new version of Crimson being drawn by @Fonthausen (see [discussion](https://groups.google.com/forum/#!topic/googlefonts-discuss/lZGJqeigS3I%5B126-150%5D)), so I foresee some clean-up and re-organizing once that is done. Stay tuned and thanks again!

**Comment by jco2** [comment]
Thanks for the heads up ! Note that this problem isn't present in the ufo branch.
Meanwhile I've switched to the font Amiri which doesn't have this issue. I'm currently working on an Opentype companion for Crimson. I got an improved build process using the scripts from Amiri too.

**Comment by dbenjaminmiller** [comment]
If you don't need semibold, Michael Sharpe's Cochineal works well. It also fixes up most of the issues which are unfortunately present in the current OTF versions of Crimson.

**Pull request merged**
