### PR TITLE
small caps ṇ for #50

### PR DESCRIPTION
**Pull request by gambhiro**
So I added the missing substitution in FontForge and generated an .otf.

FontForge seems to have made a lot of automatic adjustments to other letters as well.

It works now in the document where I needed this, but it seems to me that this isn't your usual workflow, the `bin` folder and the `.fea` files are something of a clue.

I'd be interested in learning how to apply this fix properly if you could describe it.

### CODE REVIEW

**Comment by skosch** [comment]
Thank you for the PR :) Improvements are always appreciated.

@katef, do you think you could chime in, as the author of those scripts in the `bin` folder?

**Comment by aggsol** [comment]
Any news here?

**Comment by katef** [comment]
Oh I'm sorry, I forgot to respond!

I'd added those scripts intending them to eventually become the proper way to generate an OTF file. But the feature files which @skosch gave me (with the kerning pairs and so on) referred to a lot of glyphs which weren't present, and I wasn't able to show that the generated OTF did indeed have all the same information as @skosch's original files.

As far as I know, I should've left them in a state which works. But then I got confused, and I wasn't sure how to show that my .fea files haven't accidentally lost important information.

In lieu of being able to test methodically, perhaps we ought to just go ahead and use them, and see if anybody complains...

**Comment by skosch** [comment]
Merged ­– and thanks @katef for your comment. I'll open a new issue to discuss the build process.

**Pull request merged**
