### PR TITLE
Ligatures unicode reference

### PR DESCRIPTION
**Pull request by arclabch**
Correct unicode reference for the following ligatures:
- ff
- fi
- fl
- ffi
- ffl

(Without it, ligatures don't work when used for Web or with LaTeX, haven't tried with others.)

### CODE REVIEW

**Comment by skosch** [comment]
Hey, thanks for your contribution, and sorry for the late reply :) Are those the old ligatures (read: the ugly ones from, like, 5 years ago)? Have you read the discussion on #13 ? I'm happy to consider proper ligatures, but if we're gonna put them in again (with "official" references) then we should make sure to get it right.

**Comment by arclabch** [comment]
Hi Sebastian,

I forked your repository to avoid using outdated sources. I hadn't read 
through the discussion.

My goal was to make the included ligatures work properly, since they 
should have clearly defined UTF-8 codes for most of them. And because I 
don't use a software like InDesign, I wasn't able to use them at all. 
For web usage (tried WOFF/WOFF2), they don't show up at all, even when 
leaving the full charmap in the conversion. For my main use (LaTeX), 
they don't work either. Unless you map them to their correct UTF-8 
references.

If it was the intended working (as per the discussion thread), I would 
suggest to give the ligatures UTF-8 references from the private space. 
That way, it would (theoretically) be possible to create a mapping for 
most softwares, and to hardcode the UTF-8 codes for HTML use (not 
without the side-effect mentioned by Shaun-Type regarding copy-paste). 
AFAIK, it is not possible in the current implementation.

Let me know how you want to proceed.

Have a nice day,
Lionel

**Comment by adrientetar** [comment]
> since they should have clearly defined UTF-8 codes for most of them

"Should" depends on your own definition. The use of codepoints was deprecated long ago for ligatures because they introduce semantic (encoding) differences for what is just a cosmetic difference, and doesn't allow for arbitrary character combination either. Hence why since the 2000s it is common practise to use a "smart" font technology such as OpenType which gives instructions to the shaping engine in order to replace glyph at display-time, without altering the encoding of a document.  
I note that both LuaLaTeX and XeLaTeX support such mechanisms.

But what Sebastian says is that the ligatures currently present in the font haven't been updated since an old version of Crimson and so they look out of place with the other (current) characters.  
I note that Crimson currently has a short f so as to not have to use ligatures.  
In order to reintroduce ligatures their design should be updated to current, I reckon.

**Comment by arclabch** [comment]
adrientetar: Thanks for the input, I didn't know that. However, even using XeLaTeX or LuaLaTeX with the OTF version, I was unable to make ligatures happen.

**Comment by skosch** [comment]
Sorry if I was being unclear—Adrien got it exactly right. I've left the old outlines in the files, at their obscure codepoints, without much thought. I probably shouldn't have, because it's misleading users into thinking they're a feature, not a bug :)

@arclabch, if ligatures are important to you, would you be willing to draw new ones from the existing letters, and configure the OpenType metadata correspondingly? I'd be happy to merge them in; quite frankly I'm swamped with type-unrelated work these days so I can't take care of it myself anytime soon :(

**Comment by arclabch** [comment]
Sorry for my late reply, I have been away for a while. Thank you for the clarification. It makes sense!
@skosch, I am by no means able to draw ligatures, let alone draw a single character. I will therefore wait for someone else to do it and keep them out for the time being.

**Pull request closed without merging**
